### ISSUE TITLE
Bars do not display top-down

### ISSUE THREAD

**Issue by nbedi** [wireservice/leather#72]
Not sure when this happened but reversing data in `Bars.to_svg` no longer affects the order of rendered bars.

**Comment by onyxfish** [comment]
This is a real pain. The data is being reversed correctly, but the domain isn't reversed when the scale is inferred. That is the source of truth for ordering. That is itself pretty easy to fix with a kwarg, but then the labels don't match, because their ordering is based on the domain in a totally different section of code, which is unaware of what shape is being used to render the data.
