### ISSUE TITLE
Exception generating bar chart with a text column

### ISSUE THREAD

**Issue by fconil** [wireservice/leather#80]
Hi,
I wanted to style an agate bar chart generated in the following manner :

```python
import agate
import leather

my_table = agate.Table.from_csv('mycsvdata.csv')
grp_by_status = mytable.group_by('status')
aggr_by_status = gb.aggregate([('nb', agate.Count())])
# This first chart is working fine
aggr_by_status.bar_chart('What is your status ?', 'nb', path='agate.svg')

chart = leather.Chart('What is your status ?')
chart.add_x_axis(name='status')
chart.add_y_axis(name='nb')
chart.add_bars(aggr_by_status, x='status', y='nb')
# An exception is triggered
chart.to_svg(path='leather.svg')
```
When I try to use leather, I get an exception `ValueError: 0 is not in list`.

The following code seems to reproduce the problem with simple data :

```python
import leather

mydata = [('happy', 20), ('unhappy', 10)]

mychart = leather.Chart('Reproduce problem')
mychart.add_x_axis(name='status')
mychart.add_y_axis(name='nb')
mychart.add_bars(mydata)

mychart.to_svg(path='test.svg')
```
This is happening with Python 3.5.2 and leather 0.3.2

Thanks for your libraries.

**Comment by onyxfish** [comment]
Hi Françoise, thanks for reporting this. The bug here is that the error message is bad, which I've fixed for 0.3.3, but the real issue is that bar charts have labels for the y axis, but they are first in your data. So this would work as is if you did `add_columns` instead of `add_bars`. Alternately, this works:

```
import leather

mydata = [('happy', 20), ('unhappy', 10)]

mychart = leather.Chart('Reproduce problem')
mychart.add_x_axis(name='status')
mychart.add_y_axis(name='nb')
mychart.add_bars(mydata)

mychart.to_svg(path='test.svg')
```

Resulting in:

![test](https://cloud.githubusercontent.com/assets/33046/20780095/57e1f930-b73e-11e6-8fea-33fb800d4da5.png)
